[package]
name = "hls_parse"
version = "0.1.0"
edition = "2021"
authors = ["lubezhang <lubezhang@gmail.com>"]
keywords = ["hls", "m3u8"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hls_parse"
path = "src/lib.rs"

[dependencies]
# stringreader = "0.1.1"